# NexoOS Realtime Scheduling & Memory Locking Limits for Audio & Gaming
@audio          -       rtprio          95
@audio          -       memlock         unlimited
@audio          -       nice           -19

*               soft    nofile          524288
*               hard    nofile          1048576

*               soft    memlock         unlimited
*               hard    memlock         unlimited
