# ==============================================================================
# /etc/modules-load.d/nexo-modules.conf - NexoOS Runtime Kernel Modules
# ==============================================================================

# Filesystem & Memory Acceleration
btrfs
zram
overlay
ntfs3

# Hardware Virtualization & Distrobox/Docker Isolation
kvm
kvm_intel
kvm_amd
vhost_net
tun
tap
bridge

# Direct Rendering Manager & Virtual Media Devices
amdgpu
i915
xe
v4l2loopback
uinput

# Advanced Network & Cryptographic Acceleration
tcp_bbr
wireguard
mac80211
cfg80211
